### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by faridrashidi** [szczurek-lab/DataFilter#1]
Dear DataFilter developers,

I'm attempting to use DataFilter to process a single-cell RNA dataset we have in order to generate the input for SIEVE. However, I encounter the subsequent error

`[1]    69955 segmentation fault`

The command I use is:

`datafilter --in mpileup.txt --cellNames cellnames.txt --out sieve_input.txt`

The above files can be downloaded from:

[mpileup.txt](https://drive.google.com/file/d/1MAj0EVCbmTMeWyV2vIKu2KT2WakBXZGG/view?usp=share_link)
[cellnames.txt](https://drive.google.com/file/d/1NEoEHTKmIImteVAYSMQfcL8l9d1OBgbS/view?usp=share_link)

I would highly appreciate you help!

**Comment by senbaikang** [comment]
Hi Farid,

Sorry for just seeing your question.

I think the problem is with the `cellnames.txt` file. It should be specified in the same format as for [SCIPhI](https://github.com/cbg-ethz/SCIPhI). For example, assuming that the first cell, `C13_8`, is a tumor cell, then the first line should look like `C13_8\tCT`, where `\t` is a tab space. It is the same for the rest of the lines.

Let me know if this solves your problem.

Best,
Senbai

**Comment by faridrashidi** [comment]
Got it. Thanks so much Senbai, it solved the problem :)
